version: '3.1'

services:
  rabbitMq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672


  postgresData:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecrectpass